services:
  app:
    image: ghcr.io/fsoel/studyplanner:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: file:/data/studyplanner.db
      NUXT_PUBLIC_STORAGE_MODE: backend

      # OpenID Connect configuration
      PUBLIC_URL: http://localhost:3000
      OIDC_ISSUER: https://auth.example.com
      OIDC_CLIENT_ID: your-oauth-client-id
      OIDC_CLIENT_SECRET: your-oauth-client-secret

    volumes:
      - studyplanner-data:/data
    restart: unless-stopped

volumes:
  studyplanner-data:
